import { SxProps, Theme } from "@mui/material";
import { COLORS, RADIUS, SHADOWS, TYPOGRAPHY } from "../../theme/tokens";

const interviewCoach = {
  page: {
    minHeight: "100vh",
    bgcolor: COLORS.bgLight,
    py: { xs: 4, md: 7 },
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: { xs: "flex-start", md: "center" },
    flexDirection: { xs: "column", md: "row" },
    gap: 2,
    mb: 4,
  },
  eyebrow: {
    color: COLORS.primary,
    fontWeight: 800,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    fontSize: TYPOGRAPHY.sizeXs,
  },
  title: {
    color: COLORS.textPrimary,
    fontFamily: TYPOGRAPHY.fontSerif,
    fontSize: { xs: "2.25rem", md: "3.4rem" },
    lineHeight: 1.05,
    mt: 0.75,
  },
  subtitle: {
    color: COLORS.textSecondary,
    maxWidth: 650,
    mt: 1.25,
  },
  layout: {
    display: "grid",
    gridTemplateColumns: { xs: "1fr", lg: "minmax(0, 1fr) 310px" },
    gap: 3,
    alignItems: "start",
  },
  paper: {
    bgcolor: COLORS.bgWhite,
    border: `1px solid ${COLORS.borderLight}`,
    borderRadius: RADIUS.xl,
    boxShadow: SHADOWS.sm,
  },
  setup: {
    p: { xs: 2.5, sm: 4 },
  },
  uploadBox: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    flexWrap: { xs: "wrap", sm: "nowrap" },
    p: 2,
    border: `1px dashed ${COLORS.borderMedium}`,
    borderRadius: RADIUS.lg,
    bgcolor: COLORS.surfaceSubtle,
  },
  session: {
    p: { xs: 2.5, sm: 4 },
    overflow: "hidden",
  },
  progressTrack: (questionLimit: number): SxProps<Theme> => ({
    display: "grid",
    gridTemplateColumns: `repeat(${questionLimit}, 1fr)`,
    gap: { xs: 0.5, sm: 1 },
    mb: 3,
  }),
  sessionMeta: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 2,
    flexWrap: "wrap",
    mb: 3,
  },
  timer: (remainingSeconds: number): SxProps<Theme> => ({
    fontVariantNumeric: "tabular-nums",
    fontWeight: 900,
    color: remainingSeconds <= 60 ? COLORS.danger : remainingSeconds <= 300 ? COLORS.warning : COLORS.primary,
    bgcolor: remainingSeconds <= 60 ? COLORS.dangerSoft : remainingSeconds <= 300 ? COLORS.warningSoft : COLORS.primaryPale,
    borderRadius: RADIUS.pill,
    px: 1.5,
    py: 0.5,
  }),
  progressStep: (complete: boolean, current: boolean): SxProps<Theme> => ({
    height: 6,
    borderRadius: RADIUS.pill,
    bgcolor: complete || current ? COLORS.primary : COLORS.borderLight,
    opacity: current ? 0.65 : 1,
  }),
  questionLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: 1,
    color: COLORS.primary,
    fontWeight: 800,
    fontSize: TYPOGRAPHY.sizeSm,
    mb: 1.5,
  },
  question: {
    color: COLORS.textPrimary,
    fontFamily: TYPOGRAPHY.fontSerif,
    fontSize: { xs: "1.6rem", md: "2.1rem" },
    lineHeight: 1.25,
    mb: 3,
  },
  answer: {
    "& .MuiOutlinedInput-root": {
      bgcolor: COLORS.surfaceSubtle,
      alignItems: "flex-start",
    },
  },
  actionRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 2,
    mt: 2,
    flexWrap: "wrap",
  },
  primaryButton: {
    bgcolor: COLORS.primarySurface,
    color: COLORS.onAccent,
    fontWeight: 800,
    textTransform: "none",
    px: 3,
    "&:hover": { bgcolor: COLORS.primarySurfaceDark },
  },
  feedback: {
    mt: 3,
    p: 2.5,
    borderRadius: RADIUS.lg,
    bgcolor: COLORS.primaryPale,
    borderInlineStart: `4px solid ${COLORS.primary}`,
  },
  history: {
    p: 2.5,
    position: { lg: "sticky" },
    top: { lg: 96 },
  },
  historyItem: (active: boolean): SxProps<Theme> => ({
    width: "100%",
    textAlign: "start",
    p: 1.5,
    borderRadius: RADIUS.md,
    border: `1px solid ${active ? COLORS.primary : COLORS.borderLight}`,
    bgcolor: active ? COLORS.primaryPale : "transparent",
    cursor: "pointer",
    color: COLORS.textPrimary,
    font: "inherit",
    "&:hover": { bgcolor: COLORS.bgHover },
    "&:focus-visible": { outline: `3px solid ${COLORS.primaryAlpha20}` },
  }),
  transcript: {
    display: "grid",
    gap: 2,
    mt: 4,
  },
  turn: {
    position: "relative",
    paddingInlineStart: "28px",
    pb: 0.5,
    borderInlineStart: `1px solid ${COLORS.borderMedium}`,
    "&::before": {
      content: '""',
      position: "absolute",
      insetInlineStart: -5,
      top: 8,
      width: 9,
      height: 9,
      borderRadius: "50%",
      bgcolor: COLORS.primary,
    },
  },
  turnLabel: {
    display: "block",
    mb: 0.75,
  },
  turnQuestion: {
    fontWeight: 800,
    lineHeight: 1.5,
    mb: 1.5,
  },
  turnAnswer: {
    display: "grid",
    gap: 0.5,
    p: 1.5,
    borderRadius: RADIUS.md,
    bgcolor: COLORS.surfaceSubtle,
  },
  score: {
    display: "grid",
    placeItems: "center",
    width: 88,
    height: 88,
    borderRadius: "50%",
    border: `7px solid ${COLORS.primaryAlpha20}`,
    color: COLORS.primary,
    fontWeight: 900,
    fontSize: "1.5rem",
    flexShrink: 0,
  },
  reportHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 3,
    flexWrap: "wrap",
    mb: 3,
  },
};

export default interviewCoach;
