import { COLORS, RADIUS, SHADOWS } from '../../../theme/tokens';

const planCard = {
  paperFree: {
    p: 4,
    borderRadius: RADIUS.lg,
    border: `1px solid ${COLORS.borderLight}`,
    display: 'flex',
    flexDirection: 'column' as const,
  },
  paperPro: {
    p: 4,
    borderRadius: RADIUS.lg,
    border: `2px solid ${COLORS.primary}`,
    display: 'flex',
    flexDirection: 'column' as const,
    position: 'relative' as const,
  },
  popularBadge: {
    position: 'absolute' as const,
    top: -15,
    right: 20,
    bgcolor: COLORS.primarySurface,
    color: COLORS.onAccent,
    px: 2,
    py: 0.5,
    borderRadius: RADIUS.xs,
    fontSize: '0.85rem',
    fontWeight: 'bold',
  },
  planTitle: {
    fontSize: '1.5rem',
    fontWeight: 'bold',
    color: COLORS.textPrimary,
    mb: 1,
  },
  priceFree: {
    fontSize: '2.5rem',
    fontWeight: 'bold',
    color: COLORS.textPrimary,
    mb: 1,
  },
  pricePro: {
    fontSize: '3rem',
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  priceUnit: { color: COLORS.textSecondary, fontWeight: 500 },
  priceStruck: {
    fontSize: '1.5rem',
    fontWeight: 700,
    color: COLORS.danger,
    textDecoration: 'line-through',
    textDecorationThickness: '2px',
  },
  saveBadge: {
    bgcolor: COLORS.dangerSoft,
    color: COLORS.dangerDark,
    border: `1px solid ${COLORS.dangerBorder}`,
    borderRadius: RADIUS.xs,
    px: 1,
    py: 0.25,
    fontSize: '0.78rem',
    fontWeight: 800,
    whiteSpace: 'nowrap' as const,
  },
  offerTimer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0.75,
    mb: 2,
    px: 1.5,
    py: 0.75,
    borderRadius: RADIUS.xs,
    bgcolor: COLORS.dangerSoft,
    color: COLORS.dangerDark,
    border: `1px solid ${COLORS.dangerBorder}`,
  },
  offerTimerText: {
    fontSize: '0.85rem',
    fontWeight: 800,
    fontVariantNumeric: 'tabular-nums',
  },
  priceRow: { display: 'flex', alignItems: 'baseline', gap: 1, mb: 1 },
  offerRow: { display: 'flex', alignItems: 'center', gap: 1, mb: 1 },
  pricePeriod: { color: COLORS.primary, mb: 3, fontWeight: 500, fontSize: '0.9rem' },
  validText: { color: COLORS.textSecondary, mb: 3 },
  featuresList: {
    flexGrow: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 2,
    mb: 4,
  },
  featureRow: { display: 'flex', alignItems: 'center', gap: 1.5 },
  featureIconFree: { color: COLORS.disabled, fontSize: '1.2rem' },
  featureIconPro: { color: COLORS.primary, fontSize: '1.2rem' },
  featureTextFree: { color: COLORS.textPrimary },
  featureTextPro: { color: COLORS.textPrimary, fontWeight: 500 },
  billingToggle: {
    display: 'flex',
    bgcolor: COLORS.bgLight,
    borderRadius: RADIUS.md,
    p: 0.5,
    mb: 4,
  },
  cycleActive: {
    flex: 1,
    textAlign: 'center' as const,
    py: 1,
    borderRadius: RADIUS.sm,
    cursor: 'pointer',
    bgcolor: COLORS.bgWhite,
    boxShadow: SHADOWS.sm,
    color: COLORS.textPrimary,
    fontWeight: 'bold',
    fontSize: '0.85rem',
    transition: 'all 0.2s',
  },
  cycleInactive: {
    flex: 1,
    textAlign: 'center' as const,
    py: 1,
    borderRadius: RADIUS.sm,
    cursor: 'pointer',
    bgcolor: 'transparent',
    boxShadow: 'none',
    color: COLORS.textSecondary,
    fontWeight: 'normal',
    fontSize: '0.85rem',
    transition: 'all 0.2s',
  },
  btnFree: {
    py: 1.5,
    borderRadius: RADIUS.sm,
    borderColor: COLORS.borderMedium,
    color: COLORS.textPrimary,
    '&:hover': { borderColor: COLORS.primary },
  },
  btnPro: {
    py: 1.5,
    borderRadius: RADIUS.sm,
    bgcolor: COLORS.primarySurface,
    color: COLORS.onAccent,
    boxShadow: 'none',
    '&:hover': { bgcolor: COLORS.primarySurfaceDark, boxShadow: 'none' },
  },
} as const;

export default planCard;
