import { COLORS, RADIUS, TYPOGRAPHY } from '../../../theme/tokens';

const reviewPanel = {
  root: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    color: COLORS.textPrimary,
  },
  loading: {
    minHeight: 320,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    textAlign: 'center',
    color: COLORS.primary,
  },
  eyebrow: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.75,
    color: COLORS.primary,
    fontSize: '0.72rem',
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  title: {
    fontFamily: TYPOGRAPHY.fontSerif,
    fontSize: '1.55rem',
    lineHeight: 1.15,
    color: COLORS.textPrimary,
  },
  body: {
    color: COLORS.textSecondary,
    fontSize: '0.9rem',
    lineHeight: 1.65,
  },
  guardrail: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 1,
    p: 1.5,
    borderRadius: RADIUS.md,
    bgcolor: COLORS.primaryAlpha12,
    color: COLORS.primary,
    '& .MuiTypography-root': {
      color: COLORS.textSecondary,
      fontSize: '0.78rem',
      lineHeight: 1.5,
    },
  },
  primaryButton: {
    alignSelf: 'stretch',
    bgcolor: COLORS.primarySurface,
    color: COLORS.onAccent,
    textTransform: 'none',
    fontWeight: 750,
    borderRadius: RADIUS.md,
    py: 1.15,
    boxShadow: 'none',
    '&:hover': { bgcolor: COLORS.primarySurfaceDark, boxShadow: 'none' },
  },
  retryButton: {
    alignSelf: 'flex-start',
    color: COLORS.primary,
    textTransform: 'none',
  },
  textButton: {
    color: COLORS.primary,
    textTransform: 'none',
    fontSize: '0.78rem',
    minWidth: 0,
  },
  scoreHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 1,
  },
  score: {
    fontFamily: TYPOGRAPHY.fontSerif,
    fontSize: '3.2rem',
    lineHeight: 1,
    color: COLORS.textPrimary,
  },
  progress: {
    height: 7,
    borderRadius: 8,
    bgcolor: COLORS.borderLight,
    '& .MuiLinearProgress-bar': { bgcolor: COLORS.primarySurface, borderRadius: 8 },
  },
  sectionTitle: {
    fontWeight: 800,
    fontSize: '0.85rem',
    color: COLORS.textPrimary,
  },
  findings: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1.25,
  },
  finding: {
    p: 1.5,
    borderInlineStart: `3px solid ${COLORS.accentOrange}`,
    bgcolor: COLORS.surfaceSubtle,
    borderRadius: `0 ${RADIUS.md} ${RADIUS.md} 0`,
  },
  findingTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.75,
    color: COLORS.accentOrange,
    fontWeight: 800,
    fontSize: '0.78rem',
    mb: 0.75,
  },
  dimensionScore: {
    marginInlineStart: 'auto',
    color: COLORS.accentOrange,
    fontWeight: 800,
    fontSize: '0.78rem',
  },
  findingSuggestion: {
    color: COLORS.textPrimary,
    fontSize: '0.84rem',
    lineHeight: 1.5,
    fontWeight: 600,
    '& + &': { mt: 0.75 },
  },
  rationale: {
    mt: 0.75,
    color: COLORS.textSecondary,
    fontSize: '0.74rem',
    lineHeight: 1.5,
  },
  emptyFinding: {
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    color: COLORS.primary,
    fontSize: '0.84rem',
  },
  changeList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1,
  },
  change: {
    p: 1.25,
    borderRadius: RADIUS.md,
    border: `1px solid ${COLORS.borderLight}`,
    bgcolor: COLORS.bgRaised,
  },
  changeTitle: {
    color: COLORS.primary,
    fontWeight: 800,
    fontSize: '0.75rem',
  },
  changeText: {
    color: COLORS.textPrimary,
    fontSize: '0.8rem',
    lineHeight: 1.5,
  },
} as const;

export default reviewPanel;
