import { COLORS } from '../../../theme/tokens';

const builder = {
  root: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    bgcolor: COLORS.bgLight,
    overflow: 'hidden',
    position: 'relative',
  },
  nameBar: {
    flex: '0 0 auto',
    px: 2,
    pt: { xs: 3, md: 4 },
    pb: 1.5,
    display: 'flex',
    justifyContent: 'center',
  },
  nameField: {
    width: '100%',
    maxWidth: 420,
    '& .MuiInput-input': {
      textAlign: 'center',
      fontSize: '1.05rem',
      fontWeight: 700,
      color: COLORS.textDark,
    },
  },
  stepperBar: {
    flex: '0 0 auto',
    px: 2,
    pt: 1.5,
    pb: 0.25,
    display: 'flex',
    justifyContent: 'center',
  },
  // 7 alternativeLabel steps never fit a phone, so mobile gets a compact counter instead.
  stepper: { width: '100%', maxWidth: 620, display: { xs: 'none', md: 'flex' } },
  stepperCompact: {
    display: { xs: 'flex', md: 'none' },
    alignItems: 'baseline',
    gap: 0.75,
    pt: 0.5,
  },
  stepperCompactCount: { fontSize: '0.7rem', fontWeight: 700, color: COLORS.textSecondary },
  stepperCompactSelect: {
    fontSize: '0.95rem',
    fontWeight: 700,
    color: COLORS.textDark,
    '& .MuiSelect-select': { py: 0, pr: '20px !important' },
  },
  contentRow: {
    flex: '1 1 auto',
    minHeight: 0,
    display: 'flex',
    gap: { xs: 1.5, md: 2 },
    px: { xs: 1.5, md: 2.5 },
    py: 1,
  },
  mobileSwitch: {
    display: { xs: 'flex', md: 'none' },
    justifyContent: 'center',
    px: 1.5,
    pt: 0.5,
  },
  mobileSwitchGroup: {
    '& .MuiToggleButton-root': {
      textTransform: 'none',
      fontWeight: 600,
      px: 2.5,
      py: 0.5,
      borderColor: COLORS.borderLight,
      color: COLORS.textSecondary,
      '&.Mui-selected': {
        bgcolor: COLORS.primarySurface,
        color: COLORS.onAccent,
        '&:hover': { bgcolor: COLORS.primarySurfaceDark },
      },
    },
  },
  editorPane: (showOnMobile: boolean) => ({
    flex: { xs: '1 1 auto', md: '0 0 auto' },
    width: { xs: '100%', md: 560 },
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    display: { xs: showOnMobile ? 'flex' : 'none', md: 'flex' },
    flexDirection: 'column',
  }),
  previewPane: (showOnMobile: boolean) => ({
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    bgcolor: COLORS.bgLight,
    borderRadius: 3,
    display: { xs: showOnMobile ? 'block' : 'none', md: 'block' },
  }),
  dock: {
    flex: '0 0 auto',
    display: 'flex',
    justifyContent: { xs: 'flex-start', md: 'center' },
    alignItems: 'flex-start',
    gap: { xs: 0.25, md: 4 },
    px: 1,
    overflowX: 'auto',
    py: 0.5,
    borderTop: `1px solid ${COLORS.borderLight}`,
    bgcolor: COLORS.bgWhite,
  },
  dockItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 0.25,
  },
  dockButton: {
    width: { xs: 38, md: 44 },
    height: { xs: 38, md: 44 },
    borderRadius: '50%',
    bgcolor: COLORS.bgLight,
    color: COLORS.primary,
    border: `1px solid ${COLORS.borderLight}`,
    '&:hover': { bgcolor: COLORS.primaryAlpha12 },
  },
  dockLabel: { fontSize: '0.63rem', color: COLORS.textSecondary, fontWeight: 600 },
  alertBar: {
    position: 'fixed',
    top: 12,
    left: '50%',
    transform: 'translateX(-50%)',
    zIndex: 20,
  },
  donePreview: {
    flex: '1 1 auto',
    minHeight: 0,
    overflow: 'auto',
    display: 'flex',
    flexDirection: { xs: 'column', lg: 'row' },
    justifyContent: 'center',
    gap: 2,
    p: { xs: 1.5, md: 2.5 },
  },
  donePreviewDocument: {
    flex: '1 1 auto',
    minWidth: 0,
    minHeight: { xs: 520, lg: 0 },
    overflow: 'hidden',
    display: 'flex',
  },
  doneReviewRail: {
    flex: '0 0 auto',
    width: { xs: '100%', lg: 390 },
    p: { xs: 2, md: 2.5 },
    border: `1px solid ${COLORS.borderLight}`,
    borderRadius: 3,
    bgcolor: COLORS.bgWhite,
    overflowY: { lg: 'auto' },
  },
  doneBar: {
    flex: '0 0 auto',
    display: 'flex',
    justifyContent: 'center',
    gap: { xs: 0.75, sm: 2 },
    px: 1,
    py: 1.5,
    borderTop: `1px solid ${COLORS.borderLight}`,
    bgcolor: COLORS.bgWhite,
  },
  primaryButton: {
    bgcolor: COLORS.primarySurface,
    textTransform: 'none',
    px: 4,
    borderRadius: 2,
    boxShadow: 'none',
    '&:hover': { bgcolor: COLORS.primarySurfaceDark },
  },
  secondaryButton: {
    borderColor: COLORS.primary,
    color: COLORS.primary,
    textTransform: 'none',
    px: 3,
    borderRadius: 2,
    '&:hover': {
      borderColor: COLORS.primaryDark,
      bgcolor: COLORS.primaryAlpha12,
    },
  },
  ghostButton: { textTransform: 'none', px: 3, borderRadius: 2, color: COLORS.textSecondary },
  homeButton: {
    position: 'absolute',
    left: { xs: 12, md: 24 },
    top: { xs: 8, md: 14 },
    zIndex: 100,
    bgcolor: COLORS.bgWhite,
    border: `1px solid ${COLORS.borderLight}`,
    boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
    color: COLORS.textSecondary,
    '&:hover': {
      bgcolor: COLORS.primaryAlpha12,
      color: COLORS.primary,
      borderColor: COLORS.primaryAlpha20,
    },
  },
} as const;

export default builder;
